version: "3.9"
services:
  nginx_world:
    build:
      context: /mnt/c/github/nginx-world
    image: nginx:world
    container_name: nginx_world
    ports:
      - "80:80"
  nginx_galaxy:
    build:
      context: /mnt/c/github/nginx-galaxy
    image: nginx:galaxy
    container_name: nginx_galaxy
    ports:
      - "8080:80"
  nginx_universe:
    build:
      context: /mnt/c/github/nginx-universe
    image: nginx:universe
    container_name: nginx_universe
    ports:
      - "8081:80"
