apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ .Release.Name }}
  labels:
    app: nginx-{{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: nginx-{{ .Release.Name }}
  ports:
    - name: nginx-{{ .Release.Name }}-listener
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-{{ .Release.Name }}
  labels:
    app: nginx-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: nginx-{{ .Release.Name }}
        tier: nginx
    spec:
      containers:
        - name: nginx-{{ .Release.Name }}
          image: {{ .Values.container.image }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
