name: Docker Nginx-hello CI

on: workflow_dispatch
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone git repo
      run: git clone https://github.com/igorbarnovsky/barnilla-action.git
    
    - name: Go to folder with Dockerfile
      run: cd /barnilla-action/nginx/
      
    - name: Build the Docker image
      run: docker build . -t nginx-hello:$(date +%s)

